services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PASS=game_password
    volumes:
      - ./questions.txt:/opt/scatter/questions.txt

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
